version: "2.1"

services:
  pairdrop:
    image: linuxserver/pairdrop:latest
    container_name: pairdrop
    hostname: pairdrop
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - RATE_LIMIT=false #optional
      - WS_FALLBACK=false #optional
    ports:
      - 3215:3000
    restart: unless-stopped
    #networks:
    #  - proxy
    #labels:
    #  - traefik.enable=true
    #  - traefik.http.routers.pairdrop.rule=Host(`airdrop.example.com`)
    #  - traefik.http.services.pairdrop.loadbalancer.server.port=3000
    #  - traefik.docker.network=proxy
    #  # Part for optional traefik middlewares
    #  - traefik.http.routers.pairdrop.middlewares=local-ipwhitelist@file,basic-auth@file
    #  - traefik.http.middlewares.limit.buffering.maxRequestBodyBytes=50000000 # only necessary for enabled file uploads
    #  - traefik.http.middlewares.limit.buffering.maxResponseBodyBytes=50000000 # only necessary for enabled file uploads
    #  - traefik.http.middlewares.limit.buffering.memRequestBodyBytes=50000000 # only necessary for enabled file uploads
    #  - traefik.http.middlewares.limit.buffering.memResponseBodyBytes=50000000 # only necessary for enabled file uploads    

#networks:
#  proxy:
#    external: true
