version: "3"

services:
  photoprism:
    image: photoprism/photoprism:latest  
    container_name: photoprism
    hostname: photoprism
    environment:
      - PHOTOPRISM_ADMIN_PASSWORD=MySecureLoginPasswordForPhotoprism
      - PHOTOPRISM_DEBUG=false
      - PHOTOPRISM_PUBLIC=false
      - PHOTOPRISM_UPLOAD_NSFW=true
      - PHOTOPRISM_DETECT_NSFW=false
      - PHOTOPRISM_HTTP_HOST=0.0.0.0
      - PHOTOPRISM_HTTP_PORT=2342
      - PHOTOPRISM_DATABASE_DRIVER=sqlite
    ports:
      - 2342:2342
    restart: unless-stopped
    volumes:
      - /path/to/my/locally/stored/media/files:/photoprism/originals
      - ${DOCKER_VOLUME_STORAGE:-/mnt/docker-volumes}/photoprism/storage:/photoprism/storage
