---
version: '3.7'
services:
  app:
    image: domainmod/domainmod:latest
    container_name: domainmod_app
    hostname: domainmod_app
    depends_on:
      - db
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - DOMAINMOD_WEB_ROOT=
      - DOMAINMOD_DATABASE_HOST=db
      - DOMAINMOD_DATABASE=domainmod
      - DOMAINMOD_USER=domainmod
      - DOMAINMOD_PASSWORD=password1
    volumes:
      - ${DOCKER_VOLUME_STORAGE:-/mnt/docker-volumes}/domainmod/app:/var/www/html
    ports:
      - 8080:80
    restart: unless-stopped

  db:
    image: ghcr.io/linuxserver/mariadb:alpine
    container_name: domainmod_db
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - MYSQL_DATABASE=domainmod
      - MYSQL_USER=domainmod
      - MYSQL_PASSWORD=password1
      - MYSQL_ROOT_PASSWORD=password2
    volumes:
      - ${DOCKER_VOLUME_STORAGE:-/mnt/docker-volumes}/domainmod/database:/config
    expose:
      - 3306
    restart: unless-stopped
