version: '3.3'
services:
    whoogle-search:
        ports:
            - '5000:5000'
        container_name: whoogle-search
        image: 'benbusby/whoogle-search:latest'
        restart: unless-stopped