version: "3"
services:
    gvm:
        image: securecompliance/gvm
        volumes:
          - ${DOCKER_VOLUME_STORAGE:-/mnt/docker-volumes}/greenbone/database:/opt/database
          - ${DOCKER_VOLUME_STORAGE:-/mnt/docker-volumes}/greenbone/gvm:/var/lib/gvm
          - ${DOCKER_VOLUME_STORAGE:-/mnt/docker-volumes}/greenbone/plugins:/var/lib/openvas/plugins
        environment:
          - USERNAME="admin"
          - PASSWORD="admin"
          - RELAYHOST="smtp.gmail.com"
          - SMTPPORT=465
          - AUTO_SYNC=true
          - HTTPS=true
          - TZ="Europe/Berlin"
          - SSHD=false
          - DB_PASSWORD="none"
        ports:
          - "9392:9392"  # Web interface
          #- "5432:5432" # Access PostgreSQL database from external tools
          #- "2222:22"   # SSH for remote sensors
        restart: unless-stopped
