services:

  wedding-share:
    image: cirx08/wedding_share:1.8.2
    container_name: WeddingShare
    restart: always
    ports:
      - 5000:5000/tcp
    expose:
      - 5000
    environment:
      - TITLE=WeddingShare
      - ACCOUNT_OWNER_USERNAME=admin
      - ACCOUNT_OWNER_PASSWORD=ChangeMe
      - DATABASE_TYPE=sqlite
      - ENCRYPTION_KEY=ChangeMe
      - ENCRYPTION_SALT=ChangeMe
      - THEMES_DEFAULT=dark
      - GALLERY_COLUMNS=4
      - GALLERY_ALLOWED_FILE_TYPES=.jpg,.jpeg,.png,.heic
      - GALLERY_MAX_SIZE_MB=10
      - GALLERY_REQUIRE_REVIEW=true
      - GALLERY_REVIEW_COUNTER=false
      - GALLERY_QR_CODE_ENABLED=false
      - GALLERY_MAX_SIZE_MB=4096
    volumes:
      - ${DOCKER_VOLUME_STORAGE:-/mnt/docker-volumes}/weddingshare/config:/app/config
      - ${DOCKER_VOLUME_STORAGE:-/mnt/docker-volumes}/weddingshare/uploads/thumbnails:/app/wwwroot/thumbnails
      - ${DOCKER_VOLUME_STORAGE:-/mnt/docker-volumes}/weddingshare/uploads:/app/wwwroot/uploads
      - ${DOCKER_VOLUME_STORAGE:-/mnt/docker-volumes}/weddingshare/custom_resources:/app/wwwroot/custom_resources
    #networks:
    #  - proxy
    #labels:
    #  - traefik.enable=true
    #  - traefik.docker.network=proxy
    #  - traefik.http.routers.weddingshare.rule=Host(`weddingshare.example.com`)
    #  - traefik.http.services.weddingshare.loadbalancer.server.port=5000
    #  # Optional part for file upload max sizes
    #  - traefik.http.middlewares.limit.buffering.maxRequestBodyBytes=50000000
    #  - traefik.http.middlewares.limit.buffering.maxResponseBodyBytes=50000000
    #  - traefik.http.middlewares.limit.buffering.memRequestBodyBytes=50000000
    #  - traefik.http.middlewares.limit.buffering.memResponseBodyBytes=50000000

#networks:
#  proxy:
#    external: true
