name: Renovate
on:
  schedule:
    - cron: "0 20 * * 0"
  workflow_dispatch:
permissions:
  contents: write
  pull-requests: write
jobs:
  renovate-a-m:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: renovatebot/github-action@v44.2.5
        with:
          token: ${{ secrets.RENOVATE_TOKEN }}
        env:
          RENOVATE_REPOSITORIES: ${{ github.repository }}
          LOG_LEVEL: info
          NODE_OPTIONS: "--max-old-space-size=4096"
          RENOVATE_WORKERS: 1
          RENOVATE_INCLUDE_PATHS: "examples/[a-mA-M]**"

  renovate-n-z:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: renovatebot/github-action@v44.2.5
        with:
          token: ${{ secrets.RENOVATE_TOKEN }}
        env:
          RENOVATE_REPOSITORIES: ${{ github.repository }}
          LOG_LEVEL: info
          NODE_OPTIONS: "--max-old-space-size=4096"
          RENOVATE_WORKERS: 1
          RENOVATE_INCLUDE_PATHS: "examples/[n-zN-Z]**"
