name: Renovate
on:
  schedule:
    - cron: "0 20 * * 0"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  renovate-a-f:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: renovatebot/github-action@v44.2.5
        with:
          token: ${{ secrets.RENOVATE_TOKEN }}
        env:
          RENOVATE_REPOSITORIES: ${{ github.repository }}
          LOG_LEVEL: info
          NODE_OPTIONS: "--max-old-space-size=4096"
          RENOVATE_WORKERS: 1
          RENOVATE_INCLUDE_PATHS: '["examples/a**","examples/b**","examples/c**","examples/d**","examples/e**","examples/f**"]'

  renovate-g-m:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: renovatebot/github-action@v44.2.5
        with:
          token: ${{ secrets.RENOVATE_TOKEN }}
        env:
          RENOVATE_REPOSITORIES: ${{ github.repository }}
          LOG_LEVEL: info
          NODE_OPTIONS: "--max-old-space-size=4096"
          RENOVATE_WORKERS: 1
          RENOVATE_INCLUDE_PATHS: '["examples/g**","examples/h**","examples/i**","examples/j**","examples/k**","examples/l**","examples/m**"]'

  renovate-n-s:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: renovatebot/github-action@v44.2.5
        with:
          token: ${{ secrets.RENOVATE_TOKEN }}
        env:
          RENOVATE_REPOSITORIES: ${{ github.repository }}
          LOG_LEVEL: info
          NODE_OPTIONS: "--max-old-space-size=4096"
          RENOVATE_WORKERS: 1
          RENOVATE_INCLUDE_PATHS: '["examples/n**","examples/o**","examples/p**","examples/q**","examples/r**","examples/s**"]'

  renovate-t-z:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: renovatebot/github-action@v44.2.5
        with:
          token: ${{ secrets.RENOVATE_TOKEN }}
        env:
          RENOVATE_REPOSITORIES: ${{ github.repository }}
          LOG_LEVEL: info
          NODE_OPTIONS: "--max-old-space-size=4096"
          RENOVATE_WORKERS: 1
          RENOVATE_INCLUDE_PATHS: '["examples/t**","examples/u**","examples/v**","examples/w**","examples/x**","examples/y**","examples/z**"]'
